### ISSUE TITLE
A png test error 

### ISSUE THREAD

**Issue by wyylucky** [majinxin2003/PitGen#1]
hello, I try to use PitGen to deal with a png file, I have the follow errors, is there some wrong configure?

1、pip.exe install pfp (successfully)

```
Installing collected packages: py010parser, six, sortedcontainers, intervaltree,
 pfp
  Running setup.py install for py010parser
  Running setup.py install for sortedcontainers
  Running setup.py install for intervaltree
  Running setup.py install for pfp
Successfully installed intervaltree-2.1.0 pfp-0.1.14 py010parser-0.1.6 six-1.10.
0 sortedcontainers-1.4.4
Installing collected packages: py010parser, six, sortedcontainers, intervaltree,
 pfp
  Running setup.py install for py010parser
  Running setup.py install for sortedcontainers
  Running setup.py install for intervaltree
  Running setup.py install for pfp
Successfully installed intervaltree-2.1.0 pfp-0.1.14 py010parser-0.1.6 six-1.10.
0 sortedcontainers-1.4.4
```

2、pip.exe install 010parser

```
Collecting 010parser
  Could not find a version that satisfies the requirement 010parser (from versio
ns: )
No matching distribution found for 010parser
```

3、I run an example of png

```
$ python PitGen.py -f test/F.png -t test/PNGTemplate.bt
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp3vz774
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp9hcv93
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp6mbrez
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmpwizdzn
<?xml version="1.0" encoding="utf-8"?>
<Peach version="1.0" author="MJX" >
<DataModel name="DateModel">
     <Block name="__root">
     </Block>
</DataModel>
</Peach>
```

4、what does the cpp.exe to do?

**Comment by majinxin2003** [comment]
Yeah， I got that problem too. That is becaues cpp.exe command not supporting "-x" "-c" option. You could fix the problem by modifing the 010parser's code.






At 2016-05-18 10:49:34, "Farmer" <notifications@github.com> wrote:


hello, I try to use PitGen to deal with a png file, I have the follow errors, is there some wrong configure?

1、pip.exe install pfp (successfully)

Installing collected packages: py010parser, six, sortedcontainers, intervaltree,
 pfp
  Running setup.py install for py010parser
  Running setup.py install for sortedcontainers
  Running setup.py install for intervaltree
  Running setup.py install for pfp
Successfully installed intervaltree-2.1.0 pfp-0.1.14 py010parser-0.1.6 six-1.10.
0 sortedcontainers-1.4.4
Installing collected packages: py010parser, six, sortedcontainers, intervaltree,
 pfp
  Running setup.py install for py010parser
  Running setup.py install for sortedcontainers
  Running setup.py install for intervaltree
  Running setup.py install for pfp
Successfully installed intervaltree-2.1.0 pfp-0.1.14 py010parser-0.1.6 six-1.10.
0 sortedcontainers-1.4.4


2、pip.exe install 010parser

Collecting 010parser
  Could not find a version that satisfies the requirement 010parser (from versio
ns: )
No matching distribution found for 010parser


3、I run an example of png

$ python PitGen.py -f test/F.png -t test/PNGTemplate.bt
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp3vz774
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp9hcv93
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmp6mbrez
: illegal option -- x
: illegal option -- c
cpp: Can't open input file c:\users\wyy\appdata\local\temp\tmpwizdzn
<?xml version="1.0" encoding="utf-8"?>
<Peach version="1.0" author="MJX" >
<DataModel name="DateModel">
     <Block name="__root">
     </Block>
</DataModel>
</Peach>


4、what does the cpp.exe to do?
