### ISSUE TITLE
Issue about cpp.exe command

### ISSUE THREAD

**Issue by Woniuke** [majinxin2003/PitGen#2]
Hello,My problem was similar to the first one , You have said that's becaues cpp.exe not supporting "-x" "-c" option. I have found the function named parse_string line 100 in **init**.py , I think  cpp_args should be changed ,  but I don't know  how to modify it , Could you help me?
Thanks
`def parse_string(text, parser=None, filename="<string>", optimize=True, predefine_types=True,
        use_cpp=True, cpp_path='cpp', cpp_args='', keep_scopes=False):

```
print cpp_args #Show args
cpp_args = "" #What's right option? the --xc is wrong
if use_cpp:
    with tempfile.NamedTemporaryFile("w") as f:
        f.write(text)
        f.flush()
        text = preprocess_file(f.name, cpp_path, cpp_args)`
```

**Comment by majinxin2003** [comment]
You need to modify pfp's code, deleting cpp's option.
